AWSTemplateFormatVersion: "2010-09-09"


Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "artifacts-${AWS::Region}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
              - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - s3:*
                  - iam:*
                  - codestar-connections:*
                Resource: "*"

  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyCodePipeline
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                BranchName: main
                ConnectionArn: >- 
                  arn:aws:codeconnections:us-east-1:885885860822:connection/814e63dc-c551-415a-bb99-bf05ade9445f
                FullRepositoryId: tejas-futuralis/codepipeline-cloudformation
              RunOrder: 1                                         

        - Name: DeployS3
          Actions:
            - Name: Deploy_S3
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyS3Stack
                TemplatePath: SourceOutput::s3.yaml
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt PipelineRole.Arn

        - Name: DeployIAM
          Actions:
            - Name: Deploy_IAM
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyIAMStack
                TemplatePath: SourceOutput::iam.yaml
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt PipelineRole.Arn
