AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  # GitHubOwner:
  #   Type: String
  #   Description: GitHub repository owner 
  # GitHubRepo:
  #   Type: String
  #   Description: GitHub repository name 
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to monitor
  GitHubConnectionArn:
    Type: String
    Description: Connection arn that connects to github

Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "artifacts-${AWS::Region}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
              - codepipeline.amazonaws.com
              - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - s3:*
                  - iam:*
                Resource: "*"

  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyCodePipeline
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                BranchName: !Ref GitHubBranch
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: tejas-futuralis/codepipeline-cloudformation
                PollForSourceChanges: false
              RunOrder: 1                                         

        - Name: DeployS3
          Actions:
            - Name: Deploy_S3
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyS3Stack
                TemplatePath: SourceOutput::s3.yaml
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt PipelineRole.Arn

        - Name: DeployIAM
          Actions:
            - Name: Deploy_IAM
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: MyIAMStack
                TemplatePath: SourceOutput::iam.yaml
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt PipelineRole.Arn

  Webhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      ConnectionArn: !Ref GitHubConnectionArn
      Filters:
      - JsonPath: "$.ref"
        MatchEquals: refs/heads/main
      Authentication: GITHUB_HMAC
      TargetPipeline:
        Ref: MyCodePipeline
      TargetAction: GitHub_Source
      Name: MyWebhook
      TargetPipelineVersion:
        Fn::GetAtt:
        - MyCodePipeline
        - Version
      RegisterWithThirdParty: 'true'