version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Listing folder contents:"
      - ls -R
      - echo "Zipping Lambda code…"
      - zip -r build/lambda-code.zip lambda/*
      - test -f build/lambda-code.zip || (echo "❌ zip missing!" && exit 1)
artifacts:
  base-directory: build
  files:
    - lambda-code.zip
