version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Zipping Lambda function..."
      - mkdir -p build
      - zip -r build/lambda-code.zip lambda/*
artifacts:
  base-directory: build
  files:
    - lambda-code.zip
