version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Zipping Lambda code..."
      - cd lambda
      - zip -r ../lambda-code.zip .
      - cd ..
      - echo "Uploading Lambda code to S3"
      - aws s3 cp lambda-code.zip s3://$ARTIFACT_BUCKET/lambda-code.zip

      - aws lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket $ARTIFACT_BUCKET --s3-key lambda-code.zip



artifacts:
  files:
    - lambda-code.zip
